apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    example: gateway
  name: http-db-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: http-db-service
    port: 8017
    host: http-db-service
  rules:
    - path: /.*
      methods: ["GET"]
      mutators: []
      accessStrategies:
        - handler: jwt
          config:
            trusted_issuers: ["http://dex.kyma.local"]
            required_scope: []