apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    example: gateway
  name: http-db-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: http-db-service
    name: http-db-service
    port: 8017
  rules:
    - path: /.*
      methods: ["GET"]
      mutators: []
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["foo", "bar"]