apiVersion: v1
kind: Secret
metadata:
  labels:
    example: gateway-service
  name: http-db-service
data:
  client_id: ZXhhbXBsZS1pZA==
  client_secret: ZXhhbXBsZS1zZWNyZXQ=
---
apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  labels:
    example: gateway-service
  name: http-db-service
spec:
  grantTypes:
    - "client_credentials"
  scope: "read write"
  secretName: http-db-service